const http=require('http');
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const {Pool}=require('pg');
const multer=require('multer');
const {S3Client,PutObjectCommand,GetObjectCommand,DeleteObjectCommand}=require('@aws-sdk/client-s3');

const PORT=Number(process.env.PORT||3000),ROOT=__dirname,PUBLIC=path.join(ROOT,'public');
const DATABASE_URL=process.env.DATABASE_URL||process.env.POSTGRES_URL||'';
if(!DATABASE_URL){console.error('DATABASE_URL/POSTGRES_URL is required');process.exit(1)}
const pool=new Pool({connectionString:DATABASE_URL,ssl:process.env.PGSSLMODE==='disable'?false:{rejectUnauthorized:false},max:Number(process.env.PG_POOL_MAX||10)});
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:15*1024*1024}});

const id=p=>`${p}_${Date.now().toString(36)}_${crypto.randomBytes(7).toString('hex')}`;
const hashPassword=(password,salt=crypto.randomBytes(16).toString('hex'))=>({salt,hash:crypto.scryptSync(password,salt,64).toString('hex')});
const verifyPassword=(password,row)=>{try{return crypto.timingSafeEqual(Buffer.from(hashPassword(password,row.password_salt).hash,'hex'),Buffer.from(row.password_hash,'hex'))}catch{return false}};
const json=async req=>new Promise((resolve,reject)=>{let b='';req.on('data',c=>{b+=c;if(b.length>7e6)req.destroy()});req.on('end',()=>{try{resolve(b?JSON.parse(b):{})}catch(e){reject(e)}});req.on('error',reject)});
const send=(res,status,data,headers={})=>{if(status===204){res.writeHead(204,headers);return res.end()}const body=typeof data==='string'?data:JSON.stringify(data);res.writeHead(status,{'Content-Type':'application/json; charset=utf-8',...headers});res.end(body)};
const q=async(text,params=[])=> (await pool.query(text,params)).rows;
const one=async(text,params=[])=> (await q(text,params))[0]||null;
const money=n=>Math.round((Number(n)||0)*100)/100;
const num=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;

function storageConfig(){return {bucket:process.env.AWS_S3_BUCKET,region:process.env.AWS_REGION||'auto',endpoint:process.env.AWS_S3_ENDPOINT||undefined}}
function storage(){const c=storageConfig();if(!c.bucket)throw Error('Antideploy S3 object storage is not configured (AWS_S3_BUCKET missing)');return new S3Client({region:c.region,endpoint:c.endpoint,forcePathStyle:!!c.endpoint})}

async function migrate(){
 await q(`CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,password_salt TEXT NOT NULL,name TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'owner',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await q(`CREATE TABLE IF NOT EXISTS companies(id TEXT PRIMARY KEY,name TEXT NOT NULL,owner_id TEXT NOT NULL REFERENCES users(id),gstin TEXT,financial_year_start DATE NOT NULL DEFAULT DATE '2026-04-01',currency TEXT NOT NULL DEFAULT 'INR',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await q(`CREATE TABLE IF NOT EXISTS company_members(company_id TEXT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,role TEXT NOT NULL DEFAULT 'member',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),PRIMARY KEY(company_id,user_id))`);
 await q(`CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,company_id TEXT REFERENCES companies(id) ON DELETE CASCADE,expires_at TIMESTAMPTZ NOT NULL)`);
 await q(`CREATE TABLE IF NOT EXISTS ledgers(id TEXT PRIMARY KEY,company_id TEXT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,name TEXT NOT NULL,group_name TEXT NOT NULL,type TEXT NOT NULL,opening_balance NUMERIC(18,2) NOT NULL DEFAULT 0,gstin TEXT,address TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(company_id,name))`);
 await q(`CREATE TABLE IF NOT EXISTS vouchers(id TEXT PRIMARY KEY,company_id TEXT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,voucher_no TEXT NOT NULL,voucher_type TEXT NOT NULL,voucher_date DATE NOT NULL,narration TEXT,party_ledger_id TEXT REFERENCES ledgers(id),reference_no TEXT,status TEXT NOT NULL DEFAULT 'posted',total_amount NUMERIC(18,2) NOT NULL DEFAULT 0,gst_type TEXT,gst_rate NUMERIC(6,2) NOT NULL DEFAULT 0,created_by TEXT REFERENCES users(id),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(company_id,voucher_type,voucher_no))`);
 await q(`CREATE TABLE IF NOT EXISTS voucher_entries(id TEXT PRIMARY KEY,voucher_id TEXT NOT NULL REFERENCES vouchers(id) ON DELETE CASCADE,ledger_id TEXT NOT NULL REFERENCES ledgers(id),debit NUMERIC(18,2) NOT NULL DEFAULT 0,credit NUMERIC(18,2) NOT NULL DEFAULT 0,description TEXT)`);
 await q(`CREATE INDEX IF NOT EXISTS voucher_company_date_idx ON vouchers(company_id,voucher_date DESC)`);
 await q(`CREATE INDEX IF NOT EXISTS entry_ledger_idx ON voucher_entries(ledger_id)`);
 await q(`CREATE TABLE IF NOT EXISTS contacts(id TEXT PRIMARY KEY,company_id TEXT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,kind TEXT NOT NULL,name TEXT NOT NULL,phone TEXT,gstin TEXT,email TEXT,address TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await q(`CREATE TABLE IF NOT EXISTS products(id TEXT PRIMARY KEY,company_id TEXT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,name TEXT NOT NULL,sku TEXT,hsn_sac TEXT,gst_rate NUMERIC(6,2) NOT NULL DEFAULT 0,sale_price NUMERIC(18,2) NOT NULL DEFAULT 0,purchase_price NUMERIC(18,2) NOT NULL DEFAULT 0,stock NUMERIC(18,3) NOT NULL DEFAULT 0,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(company_id,sku))`);
 await q(`CREATE TABLE IF NOT EXISTS receipts(id TEXT PRIMARY KEY,company_id TEXT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,original_name TEXT NOT NULL,mime_type TEXT NOT NULL,size_bytes INTEGER NOT NULL,object_key TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'uploaded',extracted JSONB,linked_voucher_id TEXT REFERENCES vouchers(id),created_by TEXT REFERENCES users(id),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await q(`CREATE INDEX IF NOT EXISTS contacts_company_kind_idx ON contacts(company_id,kind)`);
}
async function seedLedgers(companyId){const names=[['Cash','Cash-in-Hand','asset'],['Bank Account','Bank Accounts','asset'],['Sales','Sales Accounts','income'],['Purchase','Purchase Accounts','expense'],['Office Expenses','Indirect Expenses','expense'],['Accounts Receivable','Sundry Debtors','asset'],['Accounts Payable','Sundry Creditors','liability'],['CGST Input','Duties & Taxes','asset'],['SGST Input','Duties & Taxes','asset'],['IGST Input','Duties & Taxes','asset'],['CGST Output','Duties & Taxes','liability'],['SGST Output','Duties & Taxes','liability'],['IGST Output','Duties & Taxes','liability']];for(const [n,g,t] of names)await q(`INSERT INTO ledgers(id,company_id,name,group_name,type) VALUES($1,$2,$3,$4,$5) ON CONFLICT(company_id,name) DO NOTHING`,[id('led'),companyId,n,g,t])}
function publicUser(u){return {id:u.id,name:u.name,email:u.email,role:u.role}}
async function companiesFor(userId){return q(`SELECT c.id,c.name,c.gstin,c.currency,c.financial_year_start AS "financialYearStart",c.owner_id AS "ownerId",COALESCE(cm.role,'owner') role FROM companies c LEFT JOIN company_members cm ON cm.company_id=c.id AND cm.user_id=$1 WHERE c.owner_id=$1 OR cm.user_id=$1 ORDER BY c.created_at`,[userId])}
async function session(req){const token=(req.headers.authorization||'').replace(/^Bearer\s+/,'');if(!token)return null;return one(`SELECT s.*,u.email,u.name,u.role FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=$1 AND s.expires_at>NOW()`,[token])}
async function canCompany(userId,companyId){return !!await one(`SELECT 1 FROM companies c LEFT JOIN company_members cm ON cm.company_id=c.id AND cm.user_id=$1 WHERE c.id=$2 AND (c.owner_id=$1 OR cm.user_id=$1)`,[userId,companyId])}
function recordVoucher(v,entries){return {id:v.id,voucherNo:v.voucher_no,voucherType:v.voucher_type,date:v.voucher_date,narration:v.narration,partyLedgerId:v.party_ledger_id,referenceNo:v.reference_no,status:v.status,totalAmount:Number(v.total_amount),gstType:v.gst_type,gstRate:Number(v.gst_rate),entries:entries.map(e=>({id:e.id,ledgerId:e.ledger_id,debit:Number(e.debit),credit:Number(e.credit),description:e.description}))}}
async function getVoucher(companyId,voucherId){const v=await one(`SELECT * FROM vouchers WHERE id=$1 AND company_id=$2`,[voucherId,companyId]);if(!v)return null;return recordVoucher(v,await q(`SELECT * FROM voucher_entries WHERE voucher_id=$1 ORDER BY id`,[voucherId]))}
async function nextVoucherNo(companyId,type){const r=await one(`SELECT voucher_no FROM vouchers WHERE company_id=$1 AND voucher_type=$2 ORDER BY created_at DESC LIMIT 1`,[companyId,type]);const m=r?.voucher_no?.match(/(\d+)$/);return `${type.substring(0,3).toUpperCase()}-${String((m?Number(m[1]):0)+1).padStart(5,'0')}`}
async function postVoucher(companyId,userId,x){
 const entries=Array.isArray(x.entries)?x.entries.map(e=>({ledgerId:e.ledgerId,debit:money(e.debit),credit:money(e.credit),description:e.description||''})):[];
 if(!entries.length)throw Error('At least two ledger entries are required');
 if(entries.some(e=>e.debit<0||e.credit<0||e.debit>0&&e.credit>0))throw Error('Each entry must have either debit or credit');
 const debit=money(entries.reduce((a,e)=>a+e.debit,0)),credit=money(entries.reduce((a,e)=>a+e.credit,0));
 if(debit<=0||Math.abs(debit-credit)>0.009)throw Error(`Voucher is not balanced: debit ${debit.toFixed(2)} vs credit ${credit.toFixed(2)}`);
 for(const e of entries){if(!await one(`SELECT 1 FROM ledgers WHERE id=$1 AND company_id=$2`,[e.ledgerId,companyId]))throw Error('Ledger does not belong to this company')}
 const voucherId=id('vch'),no=x.voucherNo||await nextVoucherNo(companyId,x.voucherType||'Journal');
 const client=await pool.connect();try{await client.query('BEGIN');const v=(await client.query(`INSERT INTO vouchers(id,company_id,voucher_no,voucher_type,voucher_date,narration,party_ledger_id,reference_no,total_amount,gst_type,gst_rate,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING *`,[voucherId,companyId,no,x.voucherType||'Journal',x.date||new Date().toISOString().slice(0,10),x.narration||'',x.partyLedgerId||null,x.referenceNo||null,debit,x.gstType||null,num(x.gstRate),userId])).rows[0];for(const e of entries)await client.query(`INSERT INTO voucher_entries(id,voucher_id,ledger_id,debit,credit,description) VALUES($1,$2,$3,$4,$5,$6)`,[id('ent'),voucherId,e.ledgerId,e.debit,e.credit,e.description]);await client.query('COMMIT');return recordVoucher(v,await q(`SELECT * FROM voucher_entries WHERE voucher_id=$1 ORDER BY id`,[voucherId]))}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}

async function aiExtract(file){
 const key=process.env.OPENAI_API_KEY; if(!key)return null;
 const base64=file.buffer.toString('base64');const dataUrl=`data:${file.mimetype};base64,${base64}`;
 const model=process.env.OPENAI_MODEL||'gpt-4o-mini';
 const prompt=`Extract this Indian business receipt/invoice into strict JSON only. Fields: documentType, invoiceNo, invoiceDate (YYYY-MM-DD if known), sellerName, sellerGstin, buyerName, buyerGstin, currency, subtotal, discount, taxableValue, cgst, sgst, igst, total, paymentMode, items[{name,hsnSac,qty,rate,gstRate,amount}]. Use numbers for money. If unknown use null. Do not invent values.`;
 const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model,input:[{role:'user',content:[{type:'input_text',text:prompt},{type:'input_image',image_url:dataUrl}]}],max_output_tokens:1800})});
 if(!r.ok)throw Error(`AI extraction failed (${r.status})`);const out=await r.json();const text=out.output?.flatMap(x=>x.content||[]).map(x=>x.text||'').join('')||'';const clean=text.replace(/^```json\s*/,'').replace(/```$/,'').trim();try{return JSON.parse(clean)}catch{return {raw:text}}}

async function api(req,res,u){
 const p=u.pathname.split('/').filter(Boolean),route=p[1],rid=p[2];
 if(u.pathname==='/api/health')return send(res,200,{ok:true,service:'Acoot Smart Books',version:'5.1.0',database:'postgres',objectStorage:!!storageConfig().bucket,ai:!!process.env.OPENAI_API_KEY,time:new Date().toISOString()});
 if(route==='register'&&req.method==='POST'){const x=await json(req),email=String(x.email||'').trim().toLowerCase(),pass=String(x.password||'');if(!email||pass.length<6)return send(res,400,{error:'Valid email and password (6+ chars) required'});if(await one('SELECT 1 FROM users WHERE email=$1',[email]))return send(res,409,{error:'Email already registered'});const h=hashPassword(pass),u=await one(`INSERT INTO users(id,email,password_hash,password_salt,name) VALUES($1,$2,$3,$4,$5) RETURNING *`,[id('usr'),email,h.hash,h.salt,String(x.name||'User')]);const c=await one(`INSERT INTO companies(id,name,owner_id,gstin,currency) VALUES($1,$2,$3,$4,$5) RETURNING *`,[id('co'),String(x.companyName||'My Company'),u.id,String(x.gstin||'')||null,'INR']);await q(`INSERT INTO company_members(company_id,user_id,role) VALUES($1,$2,'owner')`,[c.id,u.id]);await seedLedgers(c.id);const token=id('tok');await q(`INSERT INTO sessions(token,user_id,company_id,expires_at) VALUES($1,$2,$3,NOW()+INTERVAL '30 days')`,[token,u.id,c.id]);return send(res,201,{token,user:publicUser(u),companies:await companiesFor(u.id),companyId:c.id})}
 if(route==='login'&&req.method==='POST'){const x=await json(req),u=await one('SELECT * FROM users WHERE email=$1',[String(x.email||'').trim().toLowerCase()]);if(!u||!verifyPassword(String(x.password||''),u))return send(res,401,{error:'Invalid email or password'});const cs=await companiesFor(u.id);if(!cs.length)return send(res,403,{error:'No company assigned'});const token=id('tok');await q(`INSERT INTO sessions(token,user_id,company_id,expires_at) VALUES($1,$2,$3,NOW()+INTERVAL '30 days')`,[token,u.id,cs[0].id]);return send(res,200,{token,user:publicUser(u),companies:cs,companyId:cs[0].id})}
 const s=await session(req);if(!s)return send(res,401,{error:'Authentication required'});
 if(route==='logout'&&req.method==='POST'){await q('DELETE FROM sessions WHERE token=$1',[(req.headers.authorization||'').replace(/^Bearer\s+/,'')]);return send(res,204,'')}
 if(route==='me')return send(res,200,{user:publicUser(s),companies:await companiesFor(s.user_id),companyId:s.company_id});
 if(route==='switch-company'&&req.method==='POST'){const x=await json(req);if(!await canCompany(s.user_id,x.companyId))return send(res,403,{error:'Company access denied'});await q(`UPDATE sessions SET company_id=$1 WHERE token=$2`,[x.companyId,(req.headers.authorization||'').replace(/^Bearer\s+/,'')]);return send(res,200,{ok:true,companyId:x.companyId})}
 if(route==='companies'&&req.method==='POST'){const x=await json(req),c=await one(`INSERT INTO companies(id,name,owner_id,gstin,currency) VALUES($1,$2,$3,$4,$5) RETURNING *`,[id('co'),String(x.name||'New Company'),s.user_id,String(x.gstin||'')||null,String(x.currency||'INR')]);await q(`INSERT INTO company_members(company_id,user_id,role) VALUES($1,$2,'owner')`,[c.id,s.user_id]);await seedLedgers(c.id);return send(res,201,c)}
 if(route==='dashboard'){const r=await one(`SELECT COALESCE(SUM(CASE WHEN v.voucher_type='Sales' THEN v.total_amount ELSE 0 END),0) sales,COALESCE(SUM(CASE WHEN v.voucher_type='Purchase' THEN v.total_amount ELSE 0 END),0) purchases,COALESCE(SUM(CASE WHEN v.voucher_type='Payment' THEN v.total_amount ELSE 0 END),0) payments,COUNT(*) transactions FROM vouchers v WHERE v.company_id=$1`,[s.company_id]);const recent=await q(`SELECT id,voucher_no AS "voucherNo",voucher_type AS "voucherType",voucher_date AS date,total_amount AS amount,narration FROM vouchers WHERE company_id=$1 ORDER BY voucher_date DESC,created_at DESC LIMIT 8`,[s.company_id]);return send(res,200,{sales:Number(r.sales),purchases:Number(r.purchases),payments:Number(r.payments),profit:Number(r.sales)-Number(r.purchases),transactions:Number(r.transactions),recent})}
 if(route==='ledgers'){if(req.method==='GET'){const rows=await q(`SELECT id,name,group_name AS "group",type,opening_balance AS "openingBalance",gstin,address FROM ledgers WHERE company_id=$1 ORDER BY name`,[s.company_id]);if(rid)return send(res,200,rows.find(x=>x.id===rid)||null);return send(res,200,rows)}if(req.method==='POST'){const x=await json(req),r=await one(`INSERT INTO ledgers(id,company_id,name,group_name,type,opening_balance,gstin,address) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id,name,group_name AS "group",type,opening_balance AS "openingBalance",gstin,address`,[id('led'),s.company_id,String(x.name),String(x.group||'General'),String(x.type||'asset'),num(x.openingBalance),x.gstin||null,x.address||null]);return send(res,201,r)}}
 if(route==='contacts'){if(req.method==='GET'){const rows=await q(`SELECT id,kind,name,phone,gstin,email,address FROM contacts WHERE company_id=$1 ORDER BY name`,[s.company_id]);return send(res,200,rows.filter(x=>!x.kind||!u.searchParams.get('kind')||x.kind===u.searchParams.get('kind')))}if(req.method==='POST'){const x=await json(req),r=await one(`INSERT INTO contacts(id,company_id,kind,name,phone,gstin,email,address) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[id('con'),s.company_id,String(x.kind||'customer'),String(x.name||''),x.phone||null,x.gstin||null,x.email||null,x.address||null]);return send(res,201,r)}}
 if(route==='products'){if(req.method==='GET')return send(res,200,await q(`SELECT id,name,sku,hsn_sac AS "hsnSac",gst_rate AS "gstRate",sale_price AS "salePrice",purchase_price AS "purchasePrice",stock FROM products WHERE company_id=$1 ORDER BY name`,[s.company_id]));if(req.method==='POST'){const x=await json(req),r=await one(`INSERT INTO products(id,company_id,name,sku,hsn_sac,gst_rate,sale_price,purchase_price,stock) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[id('prd'),s.company_id,String(x.name||''),x.sku||null,x.hsnSac||null,num(x.gstRate),num(x.salePrice),num(x.purchasePrice),num(x.stock)]);return send(res,201,r)}}
 if(route==='vouchers'){
   if(req.method==='GET'){const rows=await q(`SELECT id,voucher_no AS "voucherNo",voucher_type AS "voucherType",voucher_date AS date,narration,total_amount AS amount,status FROM vouchers WHERE company_id=$1 ORDER BY voucher_date DESC,created_at DESC`,[s.company_id]);if(rid)return send(res,200,await getVoucher(s.company_id,rid));return send(res,200,rows)}
   if(req.method==='POST'){try{return send(res,201,await postVoucher(s.company_id,s.user_id,await json(req)))}catch(e){return send(res,400,{error:e.message})}}
 }
 if(route==='vouchers'&&rid&&req.method==='GET')return send(res,200,await getVoucher(s.company_id,rid));
 if(route==='reports'&&req.method==='GET'){
   const sales=await one(`SELECT COALESCE(SUM(total_amount),0) v FROM vouchers WHERE company_id=$1 AND voucher_type='Sales'`,[s.company_id]);const purchases=await one(`SELECT COALESCE(SUM(total_amount),0) v FROM vouchers WHERE company_id=$1 AND voucher_type='Purchase'`,[s.company_id]);const gst=await one(`SELECT COALESCE(SUM(CASE WHEN v.voucher_type='Sales' AND e.ledger_id IN (SELECT id FROM ledgers WHERE name IN ('CGST Output','SGST Output','IGST Output') AND company_id=$1) THEN e.credit-e.debit ELSE 0 END),0) output_gst,COALESCE(SUM(CASE WHEN v.voucher_type='Purchase' AND e.ledger_id IN (SELECT id FROM ledgers WHERE name IN ('CGST Input','SGST Input','IGST Input') AND company_id=$1) THEN e.debit-e.credit ELSE 0 END),0) input_gst FROM vouchers v JOIN voucher_entries e ON e.voucher_id=v.id WHERE v.company_id=$1`,[s.company_id]);return send(res,200,{profitAndLoss:{sales:Number(sales.v),purchases:Number(purchases.v),netProfit:Number(sales.v)-Number(purchases.v)},gst:{output:Number(gst.output_gst),input:Number(gst.input_gst),net:Number(gst.output_gst)-Number(gst.input_gst)}})}
 if(route==='ai'&&rid==='receipt'&&req.method==='POST')return upload.single('file')(req,res,async err=>{try{if(err)throw err;if(!req.file)throw Error('Receipt file is required');const cfg=storageConfig();if(!cfg.bucket)throw Error('S3 object storage is not configured');const objectKey=`companies/${s.company_id}/receipts/${id('receipt')}-${req.file.originalname.replace(/[^a-zA-Z0-9._-]/g,'_')}`;await storage().send(new PutObjectCommand({Bucket:cfg.bucket,Key:objectKey,Body:req.file.buffer,ContentType:req.file.mimetype,Metadata:{companyId:s.company_id,uploadedBy:s.user_id}}));let extracted=null,status='uploaded';try{extracted=await aiExtract(req.file);if(extracted)status='extracted'}catch(e){console.error(e.message);status='uploaded_ai_error'}const r=await one(`INSERT INTO receipts(id,company_id,original_name,mime_type,size_bytes,object_key,status,extracted,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id,original_name AS "fileName",mime_type AS "mimeType",size_bytes AS "size",status,extracted,created_at AS "createdAt"`,[id('rec'),s.company_id,req.file.originalname,req.file.mimetype,req.file.size,objectKey,status,extracted?JSON.stringify(extracted):null,s.user_id]);return send(res,201,r)}catch(e){return send(res,400,{error:e.message})}});
 if(route==='receipts'){if(rid&&req.method==='GET'){const r=await one(`SELECT * FROM receipts WHERE id=$1 AND company_id=$2`,[rid,s.company_id]);if(!r)return send(res,404,{error:'Receipt not found'});const obj=await storage().send(new GetObjectCommand({Bucket:storageConfig().bucket,Key:r.object_key}));res.writeHead(200,{'Content-Type':r.mime_type,'Content-Disposition':`inline; filename="${r.original_name.replace(/"/g,'')}"`});return obj.Body.pipe(res)}if(req.method==='GET')return send(res,200,await q(`SELECT id,original_name AS "fileName",mime_type AS "mimeType",size_bytes AS "size",status,extracted,linked_voucher_id AS "linkedVoucherId",created_at AS "createdAt" FROM receipts WHERE company_id=$1 ORDER BY created_at DESC`,[s.company_id]))}
 return send(res,404,{error:'Unknown endpoint'});
}
function serve(req,res){let p=decodeURIComponent(new URL(req.url,'http://x').pathname);if(p==='/')p='/index.html';const f=path.normalize(path.join(PUBLIC,p));if(!f.startsWith(PUBLIC))return send(res,403,{error:'Forbidden'});fs.readFile(f,(e,b)=>{if(e)return send(res,404,{error:'Not found'});const ext=path.extname(f).slice(1);const types={html:'text/html; charset=utf-8',js:'text/javascript; charset=utf-8',css:'text/css; charset=utf-8',json:'application/json'};res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream','Cache-Control':'no-cache'});res.end(b)})}
(async()=>{try{await migrate();const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://x');if(u.pathname.startsWith('/api/'))return api(req,res,u);if(req.method==='GET')return serve(req,res);return send(res,405,{error:'Method not allowed'})}catch(e){console.error(e);send(res,500,{error:'Internal server error'})}});server.listen(PORT,()=>console.log(`Acoot Smart Books 5.1 listening on ${PORT}`))}catch(e){console.error('Startup failed:',e);process.exit(1)}})();
